language: php
git:
  depth: 1
cache:
  directories:
  - "$HOME/.composer/cache"
sudo: false
env:
  global:
  - COMPOSER_ALLOW_XDEBUG=0
matrix:
  include:
    - php: 7.1
      env: CONTAO_VERSION='4.4.*'
    - php: 7.2
      env: CONTAO_VERSION='4.4.*'
    - php: 7.1
      env: CONTAO_VERSION='4.5.*'
    - php: 7.2
      env: CONTAO_VERSION='4.5.*'
    - php: 7.2
      env: COVERAGE=1 UPDATEDOC=1 CONTAO_VERSION='4.5.*'
  allow_failures:
    - env: COVERAGE=1 UPDATEDOC=1 DEFAULT=0
  fast_finish: true
before_install:
- if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || true; fi
install:
  - composer require contao/core-bundle:${CONTAO_VERSION}
  - if [[ "$UPDATEDOC" = "1" ]]; then wget -O sami.phar http://get.sensiolabs.org/sami.phar; fi
notifications:
  email:
    recipients:
    - digitales@heimrich-hannot.de
    on_success: never
    on_failure: always
  hipchat:
    rooms:
      secure: i2CF5SCuAsSx70HzWwqhuKA9VTrYRNRLuRS/y8aw2h3BOzk273tG8JxgatgmvCVgGYP/9YsquxlnqCoonVvS2Caw3zfqdqtp35h2KBKbceI+chjhI8ead53fdVfweeXHz45afccdQEpFbC2QYBP9AIlcpjy3OjPhujnva76jZmtcR5T6QNkEtIC7kxsVJqq5znoqiz1B6xYsaYO7geBwzQPFVVt0erEqEkxiMIXgDabz8SXfTJPSSc5dwYaJFAgmCK3dF2VRXHDcc6zmcTyzouJGUxEEjyA+gwicrMKrcFURv2EUZ0+uE0sfkE1YhfKVyqEtvP1EusWBCsoAvZ8Gkgs4v02kFg8UXhoULq4WyNLciDonP6MRcMdlsHre9hpCWWv4tnpIJG7rZUOkPwuV/zbxvyNeNAd2gR76pyEutzcBUB++iq489efteBAXn5wL1LrqKolenzuwC37ylHNdoefGTmx/7pPLWnsbBmQH+pLcQk6py+4eYQIKx9cgpl6w23glyEbgulq3tw5R3Gy+8lXogbTw7Ct59CGqGebiULAAk9tdbFh92jBrgz8YBVoS3thRtbvITyMCv9faICVdrHGwv0KtIlxKnb+VpBo5OgB/P4n55gPVRdjSeL+mGSWqwgn6IGuf3p+6qYFlQ8XjLYj666mhpyqXU9o7dhC54Y8=
before_script:
  - travis_wait composer install --no-interaction
script:
  - if [[ "$COVERAGE" = "1" ]]; then mkdir -p build/logs; fi
  - if [[ "$COVERAGE" = "1" ]]; then php vendor/bin/phpunit --coverage-clover build/logs/clover.xml || true; fi
  - if [[ "$UPDATEDOC" = "1" ]]; then php sami.phar update ./docs/config/SamiDocConfig.php || true; fi
after_script:
  - if [[ "$COVERAGE" = "1" ]]; then travis_retry php vendor/bin/php-coveralls -v; fi

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build
  target-branch: gh-pages
  on:
    branch: master
    condition: "$UPDATEDOC == '1'"