huh:
  encore:
    entries:
    - { name: contao-buttermenu-bundle, file: "vendor/heimrichhannot/contao-buttermenu-bundle/src/Resources/public/js/contao-buttermenu-bundle.es6.js" }
    legacy:
      js:
      - contao-buttermenu-bundle